![logo](https://github.com/alejandrolq/Ciencia-de-Datos-en-Python/blob/main/Tareas/Tarea%202%20-%20Git/images/logo.png?raw=1)

**Nombre: José Alejandro López Quel**

**Carné: 21001127**

**Ciencia de Datos en Python**

**Sección U**

**Tarea 5**

In [14]:
import numpy as np

**Ejercicio 1 :** En data science y programación científica es común necesitar vectores con valores dentro de cierto intervalo, pero con sub-intervalos internos con diference espaciamiento ,por ejemplo:

[0.  , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.7 , 0.8 , 0.9 , 1.  ]
       
El primer sub-intervalo incrementa de 0.1 en 0.1 , el segundo de 0.01 en 0.01 , y el tercero de 0.1 en 0.1 nuevamente.

Usando unicamente NumPy crea un vector de este tipo con el nombre xs .

**nota**: no es permitido usar ciclos, debe realizarse con operaciones "vectorizadas" de numpy

In [15]:
x = np.linspace(0,0.6,6,endpoint=False,retstep=False)
y = np.linspace(0.51,0.61,10,endpoint=False,retstep=False)
z = np.linspace(0.7,1.1,4,endpoint=False,retstep=False)

xs = np.hstack((x,y,z))
xs

array([0.  , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.7 , 0.8 , 0.9 , 1.  ])

**Ejercicio 2 :** En este caso usamos un ciclo  para ejemplificar pero ya hemos mencionado que debemos evitarlos siempre que sea posible y usar operaciones "vectorizadas" ya que es mucho mas rápido al utilizar  código pre-compilado de C, en este ejercicio debemos remplazar el calculo de ys para hacerlo de manera "vectorizada" y eliminar el ciclo for. 

**tip**: usar slicing

In [16]:
import matplotlib.pyplot as plt

sample_points = 10000
inicio_intervalo = 0
ruido = 0.5*np.random.randn(sample_points) #el ruido comunmente se debe a aleatoriedad o captura no exacta de info.
x = np.linspace(inicio_intervalo,5*np.pi,sample_points) 
y = np.sin(x) + ruido

#ys es "y suavizado", inicialmente es una copia de y
ys =  y.copy()

res = np.cumsum(ys, dtype=float)
res[3:] = res[3:] - res[:-3]
result = np.hstack((ys[0], res[2:] / 3, ys[-1]))

result


array([-0.31938362, -0.23703026, -0.21313799, ..., -0.297354  ,
       -0.1746761 , -0.87627207])

**Ejercicio 3 :** Para calcular la información de una distribución de probabilidad necesitamos calcular el producto entre la información de cada posible x y su probabilidad , cada uno de estos elementos nos indica cuanta incerteza aporta cada x a la entropía de la distribución. Crea una función que calcule esto, debe recibir un vector representando a la dist. de probabilidad y devoler otro vector con el termino de entropía para cada x. Por ejemplo:

calcular_entropia([0.25,0.75])

Debe resultar en :

[0.5    ,    0.31127812]

**Nota**: la entropía es la suma sobre estos valores, en este caso no calculamos la entropía,unicamente los termimos de su sumatoria. La entropía es:

$$S = -\sum_i^nP(x_{i})log_{2}P(x_{i})$$

In [17]:
def calcular_entropia(dist_probabilidad):
  return - dist_probabilidad*np.log2(dist_probabilidad)

calcular_entropia(np.array([0.25, 0.75]))

array([0.5       , 0.31127812])

**Ejercicio 4 :** Se ha determinado también que hay costos asociados a la comunicación y relación con los clientes(llamadas,mensajes electrónicos,etc) y que estos también tienen alta correlación con el monto que estos gastan en su primer més siguiendo el modelo:
$$c(x) = (x^{2} + x + log (0.0001x)-\sqrt{0.54x})/100$$

Cree una función para calcular este modelo sobre valores de de gasto de nuevos clientes , y luego cree una función  **ganancia_neta(x,g,c)** donde:
* x = vector conteniendo los valores de gasto del primer mes para nuevos clientes.
* g = función que estima la ganancia en función de x
* c = función que estima el costo en función de x

La función realiza el calculo simple **g(x) - c(x)** , ya que es posible que los modelos cambien en el tiempo es común recibir como parámetro el modelo o modelos hijos de un modelo mas grande , en este caso eso se logra recibiendo como parámetro las funciones de ganancia y costo.

In [18]:
def ganancia2(x):
  return np.power(x,2)

def costos(x):
  return (np.power(x,2) + x + np.log(0.0001*x) - np.sqrt(0.54*x))/100

def ganancia_neta(x,g,c):
  return g(x) - c(x)

x = np.array([ -5.3,  -1. ,   0. ,   1.5,  10. , 100. ])

ganancia_neta(x,ganancia2,costos)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """


array([           nan,            nan,            inf, 2.30954875e+00,
       9.89923155e+01, 9.89911954e+03])

**Ejercicio 5 :** Usando argmax crear una función mode(x) para calcular la moda de un vector x , esta función debe devolver una tupla de 2 elementos de la forma:

(valor,conteo)

**tip** investigar y auxiliarse de otras funciones de numpy y np.argmax, no olvidar trabajar todo vectorizado, sin ciclos.

In [19]:
def mode(x):
    valores,conteo = np.unique(x, return_counts=True)
    i = np.argmax(conteo)
    return valores[i], conteo[i]

x = np.array([1,2,3,1,2,1,1,1,3,2,2,1,1,2,2,2,2,2])    
print(mode(x))

(2, 9)


**Ejercicio 6 :** Crear una función para calcular la entropía  de una distribución de probabilidad representada como un vector.
$$S = -\sum_i^nP(x_{i})log_{2}P(x_{i})$$

**Nota**: a diferencia del ejercicio anterior donde solo calculamos los términos de la entropía, en este caso  si calculamos el valor completo de la entropía, que como mencionamos es una medida de incerteza en una distribución de probabilidad.

**recordatorio**: no usar ciclos solo operaciones vectorizadas.

In [20]:
dist_a = np.array([0.3,0.5,0.2])

def calcular_entropia(dist_probabilidad):
  return - np.nansum(dist_probabilidad*np.log2(dist_probabilidad))

calcular_entropia(dist_a)

1.4854752972273344

**Ejercicio 7 :** En ML usamos la entropía cruzada como una forma de medir que tan bueno es un modelo de variables discretas a través de comparar la distribución de probabilidad que el modelo produce o predice, vs la distribución de probabilidad real dada por los datos de entrenamiento.

Podemos ver el siguiente ejemplo que define la forma en que se calcula la entropía cruzada y nos muestra un caso específico:

<img src="https://image.slidesharecdn.com/publishintroductiontodeeplearninginpythonandmatlab1-160502102437/95/introduction-to-deep-learning-in-python-and-matlab-54-638.jpg?cb=1462185644">

En este caso interpretamos así: El problema consiste en un modelo o algoritmo de ML que debe producir un vector de 3 elementos indicando la probabilidad de que ciertos datos X pertenezcan a una de 3 categorías.

* El modelo de ML produce un vector que indica que estima un 70% de probabilidad de que se trate de la categoría 0, 20% de probabilidad de que se trate de la categoría 1 y 10% de que se trate de la categoría 2.
* Los datos reales nos dicen que se trataba de un caso donde con total certeza se sabe que se trata de la categoría 0
* La entropía cruzada(a calcular en el ejercicio) nos indica que tan buena es la estimación del modelo, una EC de 0 es un modelo perfecto(en este caso un modelo que predice 100% de prob para la clase 0)

**Nota** 
* Aun que para calcular la entropía usamos logaritmos en base 2, en ML para calcular la entropía cruzada se usa logaritmo natural ya que con este se cumple el proposito **estimar que tanto se alejan las predicciones del modelo de ML de los datos reales** y es comunmente mas rápido de calcular en la computadora.
* Ya que estamos trabajando con vectores que representan distribuciones de probabilidad , podemos toparnos con lo que se conoce como : **sparse vectors**(vectores donde la mayoría de elementos son 0), esto puede producir problemas ya que le logaritmo de 0 no esta definido, tu solución debe tomar en cuenta esto y evitar que devuelva "nan"

In [21]:
def cross_entropy(Y,Y_hat):
    return - np.nansum(Y*np.log(Y_hat))    

y  = np.array([1.0,0,0])
y_hat = np.array([0.7,0.2,0.1]) # <- resultado de algun modelo predictivo

cross_entropy(y,y_hat)

0.35667494393873245

**Ejercicio 8 :** Crear una función que reciba como parámetro un vector x y calcule su magnitud o norma(euclidiana o L2) ,luego usarla para evaluar 2 vectores que representan los errores generados por 2 modelos de machine learning y concluir cual de los 2 modelos es mejor.

In [22]:
def magnitud(x):
    return np.sqrt(np.sum(np.power(x,2)))

errores_modelo1 = np.array([1,2,1,2]) 
errores_modelo2 = np.array([0,1,1,2])

print(magnitud(errores_modelo1))
print(magnitud(errores_modelo2))

if magnitud(errores_modelo1) < magnitud(errores_modelo2):
  print('El modelo 1 es mejor')
else:
  print('El modelo 2 es mejor')

3.1622776601683795
2.449489742783178
El modelo 2 es mejor


**Ejercicio 9 :** Usando la función del ejercicio anterior, crea otra función normalizar(x) que reciba de parámetro un vector x aplique normalización sobre este, el resultado debe ser un nuevo vector del tamaño de x cuya magnitud es igual a 1.0

In [23]:
def normalizar(x):
    return x/magnitud(x)
    
print(magnitud(normalizar(errores_modelo1)))
print(normalizar(errores_modelo2))

1.0
[0.         0.40824829 0.40824829 0.81649658]


**Ejercicio 10 :** Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Asumiendo que cada neurona identifica la similitud entre su entrada y la caracteística que representa concluir:
* Para cada vector de entrada Xi , cual neurona intermedia busca la característica que mas se parece a X.
* Cual vector de entrada Xi produce una activación alta(salida alta) en la capa de salida.

In [24]:
# Aplicar la red neuronal sobre los siguientes datos X
X1 = np.array([0.50,0.72])
X2 = np.array([-4,7])
X3 = np.zeros_like(X2)
X4 = np.ones_like(X1)
X5 = np.random.randn(X1.shape[0])

def neural_network(X):
  HL1 = np.array([0.25,0.37])
  HL2 = np.array([-8,14])
  OUTPUT_LAYER = [4,9]
  print("-------------")
  O_HL1 = np.dot(HL1,X)
  print('Resultado Neurona 1: ' + str(O_HL1))
  O_HL2 = np.dot(HL2,X)
  print('Resultado Neurona 2: ' + str(O_HL2))
  O_OUT_LAYER = np.dot(OUTPUT_LAYER, np.array([O_HL1, O_HL2]))
  return O_OUT_LAYER

print(neural_network(X1))
print(neural_network(X2))
print(neural_network(X3))
print(neural_network(X4))
print(neural_network(X5))


-------------
Resultado Neurona 1: 0.39139999999999997
Resultado Neurona 2: 6.08
56.2856
-------------
Resultado Neurona 1: 1.5899999999999999
Resultado Neurona 2: 130
1176.36
-------------
Resultado Neurona 1: 0.0
Resultado Neurona 2: 0
0.0
-------------
Resultado Neurona 1: 0.62
Resultado Neurona 2: 6.0
56.48
-------------
Resultado Neurona 1: -0.10977781027106936
Resultado Neurona 2: 22.756660572896305
204.37083391498246


**Respuestas**

1.   La neurona HL1 es la neurona intermedia que busca la caracteristica que mas se parece a X.
2.   El vector X2 es el que produce una activación alta en la capa de salida.



**Ejercicio 11 :** La correlación cruzada es una medida de similitud entre 2 funciones como resultado de "desplazar" una sobre la otra, comunmente es usada para encontrar características relevantes en una función desconocida o no controlada.

En procesamiento de señales por ejemplo es usada para buscar y/o filtrar en una señal que varia en el tiempo cierta caracaterística de interés. Aveces es llamada también "sliding dot product" consiste en aplicar en cada punto de una función F el producto punto con cierta función G(comunmente mas corta) y luego "deslizar" G a un nuevo punto de la función, el resultado es una nueva función H que se interpreta como :**cuanto se parece** en cada punto la función F a la característica G. 

<img src="https://i.makeagif.com/media/11-25-2015/LZ9Ufj.gif">

En este ejercicio usamos correlación cruzada para calcular las medias moviles promediando 3 puntos que ya vimos en otro ejemplo:

El primer paso es definir la función G que define el "filtro" a aplicar, para este caso consiste simplemente en un vector con 3 elementos donde cada elemento corresponde a 1/3, luego debemos aplicar el producto punto sobre cada punto de la función o datos originales(en este ejemplo llamados x) a traves aplicar el producto punto en cada elemento "corriendolo" de uno en uno

In [25]:
ruido = 0.1*np.random.randn(15) #el ruido comunmente se debe a aleatoriedad o captura no exacta de info.
x = np.linspace(0,2*np.pi,15) 
y = np.sin(x) + ruido

filtro = np.array([1/3,1/3,1/3]) #para lograr las medias moviles a traves de correlacion cruzada


**Ejercicio 12 :** Dado el vector x, usar operadores lógicos sobre vectores y acceso a  elementos usando vectores booleanos , escribir un programa que calcule eun nuevo vector z conteniendo el valor absoluto de el vector x.

**nota** No se puede usar np.abs() ni ciclos

**tip** usar un vector booleano para saber que elementos son negativos y deben ser multiplicados por -1

In [26]:
x = np.linspace(-2,2,9)

## tu codigo aqui (~ 4 linea de codigo)
### ver cuales elementos son negativos <- vector booleanos
### multiplicar esos elementos por -1
### usando el vector del rpimer paso remplazar los que eran negativos por su valor calculado en paso 2

x[x<0] = x[x<0] * -1

x

array([2. , 1.5, 1. , 0.5, 0. , 0.5, 1. , 1.5, 2. ])

**Ejercicio 13 :** Implementar la función:
$$h(x) = \begin{cases}0 & x< 0\\1 & 0<=x <=1\\0 & x> 1\end{cases}$$

Esta debe funcionar para vectores de cualquier tamaño x:

def h(x):

    ...

**nota** debe ser implementada sin ciclos o ifs 

In [27]:
def h(x):
    condiciones = [x<0 , (x>=0) & (x<=1), x > 1]
    resultados =  [0, 1, 0]
    return np.select(condiciones,resultados)

x = np.array([0.1,-2,0.5,5])
print(h(x))

[1 0 1 0]


**Ejercicio**

Usando select implementar una función k(x) con la siguiente definición:
$$k(x) = \begin{cases}-x & x< 0\\x^{3}  &0<=x<1\\x^{2}  &1<=x<2\\4  &otherwise\end{cases}$$

In [28]:
def k(x):
    condiciones = [x<0 , (x>=0) & (x<1), (x>=1) & (x<2)]
    resultados =  [-x, np.power(x,3), np.power(x,2)]
    return np.select(condiciones,resultados, 4)

x = np.array([0.1,-2,0.5,5, 1])
print(k(x))

[1.00e-03 2.00e+00 1.25e-01 4.00e+00 1.00e+00]


**Ejercicio** 
Investigar piecewise y:
*  Usarlo para implementar la función anterior de manera eficiente
*  Usar piscewise para implementar la función:

$$m(x) = \begin{cases}e^{2x} & x< 0\\1  &0<=x<1\\e^{1-x}  &x<=1\\\end{cases}$$

Nuevamente, sin utilizar ciclos ni ifs

In [29]:
def k(x):
    return np.piecewise(x, [x<0 , (x>=0) & (x<1), (x>=1) & (x<2)], [lambda x: -x, lambda x: np.power(x,3), lambda x: np.power(x,2), 4])

x = np.array([0.1,-2,0.5,5, 1])
print(k(x))

[1.00e-03 2.00e+00 1.25e-01 4.00e+00 1.00e+00]


In [30]:
def k(x):
    return np.piecewise(x, [x<0 , (x>=0) & (x<1), (x>=1)], [lambda x: np.power(np.e, 2*x), 1, lambda x: np.power(np.e, 1-x)])

x = np.array([0.1,-2,0.5,5, 1])
print(k(x))

[1.         0.01831564 1.         0.01831564 1.        ]


#### Investigar

* Proyección vectorial
    * Definir una función para calculo en numpy
    * interpretación
    * aplicación o caso de uso en DS u otras ciencias de tu interés: solo se necesita nombrar el caso de uso, no desarrollarlo o programarlo, tip: Hay un algoritmo de ML cuyo nombre puede ser  útil.
* Producto cruz
    * calculo en numpy
    * interpretación
    * aplicación o caso de uso en DS u otras ciencias de tu interés: solo se necesita nombrar el caso de uso, no desarrollarlo o programarlo

### Proyección Vectorial
#### Función para calculo en numpy
La proyección vectorial esta dada por:

<img src="https://www.geeksforgeeks.org/wp-content/ql-cache/quicklatex.com-88bbab4b50b8b737fe3ee634b2a9e23d_l3.svg">

Por lo que la función de proyección utilizando numpy se puede definir como se presenta a continuación.

In [31]:
u = np.array([1, 2, 3])   # vector u 
v = np.array([5, 6, 2])   # vector v

def proyeccion_vectorial(u, v):
    v_norm = np.sqrt(sum(v**2))
    return (np.dot(u, v)/v_norm**2)*v 
  
print("La proyección del vector u en el vector v es: ", proyeccion_vectorial(u,v)) 

La proyección del vector u en el vector v es:  [1.76923077 2.12307692 0.70769231]


#### Interpretación de la proyección vectorial

La interpretación que se le da a la proyección vectorial es la cantidad de un vector que va en dirección de otro vector dado, en otras palabras, es la componente de un vector en dirección de otro.

#### Aplicación

La proyección es un concepto muy útil y utilizado por una de las famosas técnicas de reducción de dimensionalidad conocida como PCA (Análisis de componentes principales). Cuando los datos residen en dimensiones muy altas para verlos, se tienen que proyectar a dimensiones más bajas, que es una de las partes más importantes de cualquier técnica de reducción de dimensionalidad donde estas funciones juegan un papel crucial.

### Proyección Cruz
#### Función para el calculo en numpy

En numpy existe la función cross, la cual retorna el valor del producto cruz entre dos vectores o arrays de vectores. 

```python
numpy.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
```
Donde los parametros que recibe son:

a: Componentes del primer vector (es).

b: Componentes del segundo vector (es).

axisa: Eje de a que define el (los) vector (es). Por defecto, el último eje.

axisb: Eje de b que define el (los) vector (es). Por defecto, el último eje.

axisc: Eje de c que contiene el (los) vector (es) de producto cruz. Se ignora si ambos vectores de entrada tienen dimensión 2, ya que el retorno es escalar. Por defecto, el último eje.

axis: Si está definido, el eje de a, b y c que define los vectores y los productos cruz. Anula axisa, axisb y axisc.

In [32]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

#### Interpretación de la proyección vectorial
El producto cruz es uno de los dos productos donde se multiplican dos vectores para obtener otro vector. De ahí que también se le llame producto vectorial. El vector a y el vector b cuando se multiplican de forma cruzada, nos da un vector c que es perpendicular a los vectores a y b. Una de las aplicaciones prácticas del producto cruz es el torque. Se puede observar que todos los tornillos, tapas de botellas de agua y otros objetos que involucran torque tienen ranuras diseñadas de tal manera que se mueven hacia arriba cuando se giran en sentido antihorario y viceversa.

#### Aplicación

El producto cruz desempeña un papel vital en el álgebra lineal para ayudar a resolver una amplia variedad de problemas, dentro de ellos resolver sistemas de ecuaciones. Un ejemplo práctico de esto se puede ver en la implementación de ecuaciones de predicción del modelo de regresión lineal.