![logo](https://github.com/alejandrolq/Ciencia-de-Datos-en-Python/blob/main/Tareas/Tarea%202%20-%20Git/images/logo.png?raw=1)

**Nombre: José Alejandro López Quel**

**Carné: 21001127**

**Ciencia de Datos en Python**

**Sección U**

**Ejercicios Finales**

**Ejercicio**: Investigar y ejemplificar diferencias entre np.array y np.matrix

# Numpy Array

Un array de numpy (ndarray) es una cuadrícula de valores, todos del mismo tipo, el cual está indexado por una tupla de enteros no negativos. El número de dimensiones es el rango del array; la forma de una matriz es una tupla de números enteros que dan el tamaño del array a lo largo de cada dimensión. Algunas de las ventajas clave de los arrays numpy es que son rápidos, faciles de trabajar con ellos, y ofrece a los usuarios la oportunidad de realizar cálculos a través de arrays completos.

Al igual que con otros objetos contenedores en Python, se puede acceder al contenido de un array y modificarlo indexando o dividiendo el arreglo (usando, por ejemplo, N enteros) y mediante los métodos y atributos del ndarray.

Diferentes ndarrays pueden compartir los mismos datos, por lo que los cambios realizados en un ndarray pueden ser visibles en otro. Es decir, un ndarray puede ser una "vista" de otro ndarray, y el ndarray "base" se ocupa de los datos a los que se refiere. ndarrays también pueden ser vistas a la memoria propiedad de cadenas u objetos de Python que implementan las interfaces de búfer o matriz.

In [4]:
import numpy as np

In [5]:
# Declaración de un array de numpy

x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Propiedades

# Numero de dimensiones
x.ndim

2

In [7]:
# Forma
x.shape

(2, 3)

In [8]:
# Indexado
x [0]

array([1, 2, 3])

# Numpy Matrix

Una matriz de numpy es una matriz de dos dimensiones, especializada que conserva su naturaleza de dos dimensiones a través de operaciones. Tiene ciertos operadores especiales, como * (multiplicación de matrices) y ** (potencia de matriz).

In [17]:
# Declaración de una matriz de numpy

x = np.matrix([[1, 2], [3, 4]])
x

matrix([[1, 2],
        [3, 4]])

In [18]:
# Propiedades

# Numero de dimensiones
x.ndim

2

In [19]:
# Forma
x.shape

(2, 2)

In [20]:
# Indexado
x [0]

matrix([[1, 2]])

## Operaciones de numpy arrays y matrices

### Suma

In [22]:
# Suma Numpy Arrays
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
print(A+B)
# Suma Numpy Matrix
A = np.matrix([[2, 4], [5, -6]])
B = np.matrix([[9, -3], [3, 6]])
print(A+B)


[[11  1]
 [ 8  0]]
[[11  1]
 [ 8  0]]


### Resta

In [24]:
# Resta Numpy Arrays
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
print(A-B)
# Resta Numpy Matrix
A = np.matrix([[2, 4], [5, -6]])
B = np.matrix([[9, -3], [3, 6]])
print(A-B)

[[ -7   7]
 [  2 -12]]
[[ -7   7]
 [  2 -12]]


### Multiplicación

#### Producto punto

In [28]:
# Producto punto Numpy Arrays
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
print(A.dot(B))
# Producto punto Numpy Matrix
A = np.matrix([[2, 4], [5, -6]])
B = np.matrix([[9, -3], [3, 6]])
print(A.dot(B))

[[ 30  18]
 [ 27 -51]]
[[ 30  18]
 [ 27 -51]]


### Transpuesta

In [36]:
# Transpuesta Numpy Array
A = np.array([[1, 1], [2, 1]])
print(A.T)
# Transpuesta Numpy Matrix
A = np.matrix([[1, 1], [2, 1]])
print(A.T)

[[1 2]
 [1 1]]
[[1 2]
 [1 1]]


# Diferencia entre Numpy Array y Numpy Matrix

La principal diferencia entre estos dos tipos de elementos es de que las matrices numpy son estrictamente **bidimensionales**, mientras que los array de numpy (ndarrays) son **N-dimensionales**. Los objetos matrix son una subclase de ndarray, por lo que heredan todos los atributos y métodos de ndarrays, tal y como se muestra en los ejemplos anteriores.

# Ejercicio 1 Notebook 8

**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicación de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producirá una nueva matriz con el mismo número de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la función "sigmoid"(descrita a continuación) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamaño pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la función sigmoid. El resultado debe ser un tensor con el mismo número de filas que la matriz X y una sola columna(una predicción para cada fila de X.

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [10]:
import numpy as np

In [11]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    return 1/(1+np.exp(-x))

In [87]:
def neural_network(X):
    H_W = np.array([[0.25,0.37],
                    [-8,14]])
    OL_W = np.array([[4],[9]])
    O_HL = np.matmul(H_W,X)
    O_HL = sigmoid(O_HL)
    O_OUT_LAYER = np.matmul(O_HL, OL_W)
    O_OUT_LAYER = sigmoid(O_OUT_LAYER)
    return O_OUT_LAYER

In [88]:
X =  np.array([[0.1,0.2],
               [1,2]])
neural_network(X)

array([[0.99981229],
       [0.99999774]])

### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [13]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

In [159]:
def relu(x):
    return np.maximum(0,x)

In [161]:
def neural_network(X, act):
    H_W = np.array([[0.712, 0.355, 0.268], [0.112, 0.855, 0.468]])
    OL_W = np.matmul(X, H_W)
    OL_W = act(OL_W)
    HL_W = np.array([[0.116], [0.329], [0.708]])
    OL_HLW = np.matmul(OL_W, HL_W)
    OL_HLW = act(OL_HLW)
    return OL_HLW

In [166]:
X= np.array([[1,1]])
print(neural_network(X, sigmoid))
print(neural_network(X, relu))

[[0.69269553]]
[[1.014762]]


In [167]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])
print(neural_network(X, sigmoid))
print(neural_network(X, relu))

[[0.70244573]
 [0.66259284]
 [0.75933678]
 [0.75973948]
 [0.75802295]
 [0.6739704 ]
 [0.75954693]
 [0.76005845]
 [0.75952743]
 [0.76005845]]
[[1.2901751e+00]
 [3.9827325e-01]
 [7.5763340e+00]
 [8.4233580e+00]
 [5.8520720e+00]
 [6.1724410e-01]
 [7.7977270e+00]
 [1.6403930e+02]
 [7.7289650e+00]
 [1.0551858e+03]]
